### ISSUE TITLE
link category redirect page also in category navigation by default

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#78]
In each category you can set a redirect page. However, this redirect page is only considered for the category list in each news item, but not for the general category navigation by default. As mentioned here https://github.com/codefog/contao-news_categories/issues/73#issuecomment-159927146 I am using [this gist](https://gist.github.com/fritzmg/81266c77526262fbbf0a) to also link the category to its redirect page, if set. It would be cool if the category navigation module did this by default.

Or is there a special reason, why it doesn't do it in the first place?

**Comment by qzminski** [comment]
The news categories list front end module acts like a filter for the other news modules whereas the initial concept of the redirect page field in the category settings was to point to the page that contains pre-filtered front end modules. Your idea puts an equality sign between those two which is not essentially true.

It cannot be introduced now because of backwards compatibility anyway, so I will leave the ticket open for the next major release.

**Comment by fritzmg** [comment]
Ok, fair enough :)

**Comment by qzminski** [comment]
Implemented in 328d1b4.
